project:
  type: website
  output-dir: docs

website: 
  title: "Jan Sauermann"
  navbar: 
    search: true
    left:
      - href: index.qmd
        text: "Home"
      - research.qmd 
      - teaching.qmd
      - text: "Education workshop"
        file: educworkshop.qmd
      - seminars.qmd  
    tools: 
      - icon: mailbox
        href: mailto:jan.sauermann@ifau.uu.se
      - icon: cloud-sun
        href: https://bsky.app/profile/jansauermann.bsky.social
      - icon: linkedin 
        href: https://www.linkedin.com/in/jansauermann
  page-footer: 
    left: "&copy; 2024, [Jan Sauermann](mailto:jan.sauermann@ifau.uu.se)" 
    right: "[IFAU](https://www.ifau.se/en/), Kyrkogårdsgatan 6, SE-753 12 Uppsala"
      
format:
  html:
    theme: lumen
    css: styles.css
    toc: true
    callout-appearance: minimal
    link-external-icon: false
    link-external-newwindow: true




