---
title: "Master Seminar University of Würzburg (summer term 2024)"
format: 
  html: 
    theme: callout_research.scss
---

**Company policies, public policies, and the organization of the firm**

# Introduction

Companies create and adapt policies to, amongst others, motivate employees and improve hiring of new employees. At the same time, firms are also affected by public policies that are introduced to improve upon societal goals, such as gender equality. The seminar draws on research in personnel economics and labor economics to study firm-level and public policies and how they affect firm-level outcomes, such as hiring, wages, and career progression.

Participants are provided with eight topics to choose from (a more detailed version with references will be provided to all registered students): 

1. The impact of workplace training on performance and wages
2. Peer effects in firms
3. Working from home
4. Employer learning and beliefs
5. Policies to reduce gender gaps within firms
6. Productivity effects of the minimum wage
7. Networks and promotions
8. Individual versus team incentives

In February 2024, all registered students will be asked for their preference and students will be assigned to each of the topics.

The course gives 10 ECTS. Students will need to write a term paper, present it in the seminar, present a shorter comment on another student's presentation, and participate in the discussion. The course language is English.
   
***

# Organization
## Contact
The course is led by [Associate Professor Jan Sauermann, IFAU Uppsala](https://sites.google.com/site/jansauermann/home). If you have any questions, comments, or would like to talk via zoom, please do not hesitate to send an email ([jan.sauermann@ifau.uu.se](mailto:jan.sauermann@ifau.uu.se)).

## Important dates
- Registration deadline: December 12, 2023 [(application through Flip)](https://flip.wiwi.uni-wuerzburg.de/)
- Kick-off seminar (virtual): April 16, 2024 (10:00-11:30) (Zoom link TBA)
- Mid-term meeting (virtual): May 14, 2024 (10:00-11:30) (Zoom link TBA)
- Seminar (in person): June 2024 (University of Würzburg, Room TBA)
- Final deadline for term papers: TBA [(by email to jan.sauermann@ifau.uu.se)](mailto:jan.sauermann@ifau.uu.se)

# Guidelines and format

## Term paper
Each student needs to write and hand in a term paper. The studies in the outline are only the first step. Careful literature search and critical reading of the literature will be an integral part of the students' work. For the term paper itself, it is very important to critically discuss the existing literature as well as theoretical concepts and empirical strategies. Students may use gather data to support arguments but can also entirely rely on arguments from articles.

Regarding the formal requirements, the Chair has provided [formal references (pdf)](https://www.wiwi.uni-wuerzburg.de/fileadmin/12020700/2021/Englisch_Formale_Hinweise_fuer_wissenschaftliche_Arbeiten_08112021.pdf). To clarify, I will add some common remarks here as well (list will be updated):

- Term papers need to be written in English
- Term papers may at most be 20 pages of text. This _includes_ any tables and figure, but _excludes_ table of contents, assurance, and references.
- Please use in-text citations (such as "as shown by Mayer (2008)" or "text here (Mayer, 2008)."). Most of the assigned papers follow this style.

## Presentation
Each student needs to present his/her term paper. The presentation needs to be done in English. In the case that two students are assigned to the same topic, both students should together present their thesis in a joint presentation. Each presentation is supposed to be no longer than 15 minutes. 

- There is no need to submit the slides before or after the seminar
- Students can use handouts but this is no requirement

## Comment
Each student needs to comment on other term paper. There is no need to submit comments in written form. Slides can be useful for presenting the comment (but are not required). 
The comments are only about 5 minutes so there is not much time. The idea of the comment is to first give a (very) short summary and then to add own ideas, critical questions or additional input for example from your own topic. Comments should be critical yet polite. Optimally, the comments together with the term paper presentation can stimulate a discussion in which all students can participate. 

## Discussion
After the term paper presentation and comment, the floor is open for all to ask questions or add own thoughts to the topic. Fair and constructive comments and contributions are a public good for the entire group.

# Updates
TBA

# Frequently asked questions
TBA
